# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 626171fa1a98a8f4d7177da4ac9337e71ed6c4ed3164cda8684759b4fe645edcac4c4de6df6a5059d51b9e03e7fcafab18cd6745358127e5b807b9b330340bb9

test:
  secret_key_base: 0d5ee090ae6e57a7f5e6ece3aa235e7d173df47e49879fcfe90bf69342a2d229d25fbe32612e5da8dc7c8f0e639ee07a20bae93be5d51e353a71ce384ade314c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
